#1. KUTUPHANELER

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data= pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
data['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
data['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [ ]:
data.drop(columns=['RowNumber',	'CustomerId',	'Surname'], inplace=True)

In [ ]:
data.sample(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7571,718,France,Male,52,8,79475.30,3,1,1,32421.32,1
5771,623,Spain,Male,44,1,83325.77,1,0,1,80828.78,0
5364,812,Germany,Male,33,2,127154.14,2,0,1,105383.49,0
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
3876,565,Germany,Male,31,2,89558.39,2,1,1,4441.54,0

In [ ]:
x=data.iloc[:,3:-1]
y=data.iloc[:,-1]

In [ ]:
data["Gender"].unique()
x['Gender']=data['Gender'].replace({'Female':0, 'Male':1})
print(x)

      Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      42       2       0.00              1          1               1
1      41       1   83807.86              1          0               1
2      42       8  159660.80              3          1               0
3      39       1       0.00              2          0               0
4      43       2  125510.82              1          1               1
...   ...     ...        ...            ...        ...             ...
9995   39       5       0.00              2          1               0
9996   35      10   57369.61              1          1               1
9997   36       7       0.00              1          0               1
9998   42       3   75075.31              2          1               0
9999   28       4  130142.79              1          1               0

      EstimatedSalary  Gender
0           101348.88       0
1           112542.58       0
2           113931.57       0
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       1
9996        101699.77       1
9997         42085.58       0
9998         92888.52       1
9999         38190.78       0

[10000 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x=sc.fit_transform(x)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
y =np.array(y)
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
ulke=data.iloc[:,0:1].values
print(ulke)

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

le = LabelEncoder()

ulke[:,0]= le.fit_transform(ulke[:,0])

onehotencoder = OneHotEncoder()
ulke= onehotencoder.fit_transform(ulke).toarray()
ulke=x[:,1:]

[[619]
 [608]
 [502]
 ...
 [709]
 [772]
 [792]]

In [ ]:
sonuc = pd.DataFrame(data)
print(sonuc)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1
1             608     Spain  Female   41       1   83807.86              1
2             502    France  Female   42       8  159660.80              3
3             699    France  Female   39       1       0.00              2
4             850     Spain  Female   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France    Male   39       5       0.00              2
9996          516    France    Male   35      10   57369.61              1
9997          709    France  Female   36       7       0.00              1
9998          772   Germany    Male   42       3   75075.31              2
9999          792    France  Female   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary  Exited
0             1               1        101348.88       1
1             0               1        112542.58       0
2             1               0        113931.57       1
3             0               0         93826.63       0
4             1               1         79084.10       0
...         ...             ...              ...     ...
9995          1               0         96270.64       0
9996          1               1        101699.77       0
9997          0               1         42085.58       1
9998          1               0         92888.52       1
9999          1               0         38190.78       0

[10000 rows x 11 columns]

In [ ]:
# TEST - TRAIN OLARAK IKIYE BOLME
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
# VERILERIN OLCEKLENMESI
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [ ]:
from tensorflow.keras.callbacks import ReduceLROnPlateau
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
import datetime
from keras.metrics import Recall,Precision
from tensorflow.keras.utils import plot_model
from IPython.display import SVG, Image
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPool2D, Dense, Dropout, Flatten
from keras.layers import BatchNormalization
from keras.layers import Activation
!pip install optuna
from optuna import create_study, Trial
from tensorflow.keras.optimizers import Adam

Collecting optuna
  Downloading optuna-3.5.0-py3-none-any.whl (413 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.4/413.4 kB 5.5 MB/s eta 0:00:00
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.13.1-py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 10.1 MB/s eta 0:00:00
Collecting colorlog (from optuna)
  Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (23.2)
Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.28)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.66.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.1)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.2-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 10.9 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.10.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna) (3.0.3)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.2 alembic-1.13.1 colorlog-6.8.2 optuna-3.5.0

In [ ]:
# Amaç fonksiyonunu tanımlayın
def objective(trial):
    n_layers = trial.suggest_int("n_layers", 1, 10)
    n_units = trial.suggest_int("n_units", 32, 256)
    learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-2)

    # Modeli oluşturun ve eğitin
    model = Sequential()
    model.add(Dense(n_units, activation="relu", input_shape=(x_train.shape[1],)))  # Input layer with explicit input shape
    for _ in range(n_layers - 1):  # Adjust loop for hidden layers only
        model.add(Dense(n_units, activation="relu"))
    model.add(Dense(1, activation="sigmoid"))  # Output layer for binary classification
    model.compile(loss="binary_crossentropy", optimizer=Adam(learning_rate=learning_rate),  metrics=['accuracy'])
    model.fit(x_train, y_train, epochs=10)

    # Doğrulama setinde değerlendirme
    loss, _ = model.evaluate(x_test, y_test)
    return loss

In [ ]:
#Optuna çalışması oluştur
study = create_study(direction="minimize")

# Hiperparametreleri optimize edin
study.optimize(objective, n_trials=100)

#En iyi parametrelere erişin
best_params = study.best_params

# En iyi parametreleri ve puanı yazdırın
print(f"Best params: {best_params}")
print(f"Best validation loss: {study.best_value}")

[I 2024-03-13 14:56:05,506] A new study created in memory with name: no-name-573069d4-dfaa-43a3-8b73-78edbb4b7eb3

Epoch 1/10
250/250 [==============================] - 3s 6ms/step - loss: 0.4038 - accuracy: 0.8294
Epoch 2/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3621 - accuracy: 0.8505
Epoch 3/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3590 - accuracy: 0.8528
Epoch 4/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3521 - accuracy: 0.8541
Epoch 5/10
250/250 [==============================] - 2s 7ms/step - loss: 0.3487 - accuracy: 0.8551
Epoch 6/10
250/250 [==============================] - 2s 9ms/step - loss: 0.3441 - accuracy: 0.8610
Epoch 7/10
250/250 [==============================] - 2s 6ms/step - loss: 0.3461 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3435 - accuracy: 0.8591
Epoch 9/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3378 - accuracy: 0.8612
Epoch 10/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3351 - accuracy: 0.8580
63/63 [==============================] - 0s 3ms/step - loss: 0.3636 - accuracy: 0.8555

[I 2024-03-13 14:56:28,250] Trial 0 finished with value: 0.36358287930488586 and parameters: {'n_layers': 6, 'n_units': 215, 'learning_rate': 0.001124924341157312}. Best is trial 0 with value: 0.36358287930488586.

Epoch 1/10
250/250 [==============================] - 4s 6ms/step - loss: 0.4254 - accuracy: 0.8142
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3763 - accuracy: 0.8440
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3677 - accuracy: 0.8508
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3661 - accuracy: 0.8506
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3617 - accuracy: 0.8518
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3623 - accuracy: 0.8506
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3549 - accuracy: 0.8555
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3543 - accuracy: 0.8546
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3531 - accuracy: 0.8540
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3527 - accuracy: 0.8528
63/63 [==============================] - 0s 2ms/step - loss: 0.3648 - accuracy: 0.8540

[I 2024-03-13 14:56:40,506] Trial 1 finished with value: 0.36479344964027405 and parameters: {'n_layers': 7, 'n_units': 119, 'learning_rate': 0.0056132707090005155}. Best is trial 0 with value: 0.36358287930488586.

Epoch 1/10
250/250 [==============================] - 3s 5ms/step - loss: 0.4126 - accuracy: 0.8250
Epoch 2/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3637 - accuracy: 0.8501
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3580 - accuracy: 0.8535
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3516 - accuracy: 0.8540
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3501 - accuracy: 0.8594
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3441 - accuracy: 0.8585
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3417 - accuracy: 0.8587
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.8599
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3389 - accuracy: 0.8614
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8612
63/63 [==============================] - 0s 2ms/step - loss: 0.3618 - accuracy: 0.8530

[I 2024-03-13 14:56:51,209] Trial 2 finished with value: 0.3618412911891937 and parameters: {'n_layers': 6, 'n_units': 126, 'learning_rate': 0.001441660608465153}. Best is trial 2 with value: 0.3618412911891937.

Epoch 1/10
250/250 [==============================] - 3s 6ms/step - loss: 0.4471 - accuracy: 0.8075
Epoch 2/10
250/250 [==============================] - 2s 9ms/step - loss: 0.4027 - accuracy: 0.8306
Epoch 3/10
250/250 [==============================] - 2s 8ms/step - loss: 0.3800 - accuracy: 0.8489
Epoch 4/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4120 - accuracy: 0.8294
Epoch 5/10
250/250 [==============================] - 2s 6ms/step - loss: 0.4271 - accuracy: 0.8261
Epoch 6/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4472 - accuracy: 0.8179
Epoch 7/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4275 - accuracy: 0.8271
Epoch 8/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4893 - accuracy: 0.8073
Epoch 9/10
250/250 [==============================] - 1s 6ms/step - loss: 0.5065 - accuracy: 0.7960
Epoch 10/10
250/250 [==============================] - 2s 7ms/step - loss: 0.5065 - accuracy: 0.7960
63/63 [==============================] - 0s 2ms/step - loss: 0.5039 - accuracy: 0.7975

[I 2024-03-13 14:57:14,200] Trial 3 finished with value: 0.5038605332374573 and parameters: {'n_layers': 9, 'n_units': 201, 'learning_rate': 0.008842349049334735}. Best is trial 2 with value: 0.3618412911891937.

Epoch 1/10
250/250 [==============================] - 4s 8ms/step - loss: 0.4222 - accuracy: 0.8200
Epoch 2/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3797 - accuracy: 0.8479
Epoch 3/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3656 - accuracy: 0.8519
Epoch 4/10
250/250 [==============================] - 2s 8ms/step - loss: 0.3620 - accuracy: 0.8525
Epoch 5/10
250/250 [==============================] - 2s 8ms/step - loss: 0.3596 - accuracy: 0.8504
Epoch 6/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3534 - accuracy: 0.8540
Epoch 7/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3556 - accuracy: 0.8569
Epoch 8/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3537 - accuracy: 0.8539
Epoch 9/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3538 - accuracy: 0.8545
Epoch 10/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3490 - accuracy: 0.8575
63/63 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8540

[I 2024-03-13 14:57:31,617] Trial 4 finished with value: 0.34958431124687195 and parameters: {'n_layers': 9, 'n_units': 170, 'learning_rate': 0.002648972666257221}. Best is trial 4 with value: 0.34958431124687195.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4181 - accuracy: 0.8209
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3770 - accuracy: 0.8461
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3742 - accuracy: 0.8474
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3642 - accuracy: 0.8515
Epoch 5/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3571 - accuracy: 0.8541
Epoch 6/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3529 - accuracy: 0.8539
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3514 - accuracy: 0.8547
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3515 - accuracy: 0.8553
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3470 - accuracy: 0.8574
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3496 - accuracy: 0.8551
63/63 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8605

[I 2024-03-13 14:57:43,947] Trial 5 finished with value: 0.3498840928077698 and parameters: {'n_layers': 8, 'n_units': 79, 'learning_rate': 0.004455004240166389}. Best is trial 4 with value: 0.34958431124687195.

Epoch 1/10
250/250 [==============================] - 3s 6ms/step - loss: 0.4691 - accuracy: 0.8041
Epoch 2/10
250/250 [==============================] - 2s 6ms/step - loss: 0.4298 - accuracy: 0.8213
Epoch 3/10
250/250 [==============================] - 2s 9ms/step - loss: 0.3910 - accuracy: 0.8407
Epoch 4/10
250/250 [==============================] - 2s 7ms/step - loss: 0.4039 - accuracy: 0.8219
Epoch 5/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3963 - accuracy: 0.8416
Epoch 6/10
250/250 [==============================] - 1s 5ms/step - loss: 0.4357 - accuracy: 0.8242
Epoch 7/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4736 - accuracy: 0.8202
Epoch 8/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4376 - accuracy: 0.8315
Epoch 9/10
250/250 [==============================] - 1s 5ms/step - loss: 0.5684 - accuracy: 0.8334
Epoch 10/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4069 - accuracy: 0.8336
63/63 [==============================] - 0s 2ms/step - loss: 0.3834 - accuracy: 0.8255

[I 2024-03-13 14:58:06,869] Trial 6 finished with value: 0.3834059238433838 and parameters: {'n_layers': 10, 'n_units': 184, 'learning_rate': 0.007041947341043145}. Best is trial 4 with value: 0.34958431124687195.

Epoch 1/10
250/250 [==============================] - 4s 10ms/step - loss: 0.4221 - accuracy: 0.8231
Epoch 2/10
250/250 [==============================] - 2s 10ms/step - loss: 0.3985 - accuracy: 0.8374
Epoch 3/10
250/250 [==============================] - 3s 14ms/step - loss: 0.3879 - accuracy: 0.8460
Epoch 4/10
250/250 [==============================] - 3s 11ms/step - loss: 0.3765 - accuracy: 0.8482
Epoch 5/10
250/250 [==============================] - 2s 9ms/step - loss: 0.3658 - accuracy: 0.8487
Epoch 6/10
250/250 [==============================] - 2s 9ms/step - loss: 0.3593 - accuracy: 0.8499
Epoch 7/10
250/250 [==============================] - 2s 9ms/step - loss: 0.3564 - accuracy: 0.8549
Epoch 8/10
250/250 [==============================] - 3s 12ms/step - loss: 0.3619 - accuracy: 0.8533
Epoch 9/10
250/250 [==============================] - 3s 14ms/step - loss: 0.3572 - accuracy: 0.8524
Epoch 10/10
250/250 [==============================] - 2s 9ms/step - loss: 0.3510 - accuracy: 0.8543
63/63 [==============================] - 0s 3ms/step - loss: 0.3571 - accuracy: 0.8625

[I 2024-03-13 14:58:50,006] Trial 7 finished with value: 0.3570704162120819 and parameters: {'n_layers': 8, 'n_units': 243, 'learning_rate': 0.00432092523185652}. Best is trial 4 with value: 0.34958431124687195.

Epoch 1/10
250/250 [==============================] - 2s 4ms/step - loss: 0.4037 - accuracy: 0.8299
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3693 - accuracy: 0.8476
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3616 - accuracy: 0.8533
Epoch 4/10
250/250 [==============================] - 1s 6ms/step - loss: 0.3548 - accuracy: 0.8534
Epoch 5/10
250/250 [==============================] - 2s 6ms/step - loss: 0.3530 - accuracy: 0.8566
Epoch 6/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3550 - accuracy: 0.8536
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3517 - accuracy: 0.8568
Epoch 8/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3510 - accuracy: 0.8572
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3460 - accuracy: 0.8602
Epoch 10/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3428 - accuracy: 0.8596
63/63 [==============================] - 0s 2ms/step - loss: 0.3550 - accuracy: 0.8525

[I 2024-03-13 14:59:11,943] Trial 8 finished with value: 0.3549758493900299 and parameters: {'n_layers': 4, 'n_units': 212, 'learning_rate': 0.0036086333527260745}. Best is trial 4 with value: 0.34958431124687195.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4250 - accuracy: 0.8195
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3740 - accuracy: 0.8453
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8494
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3585 - accuracy: 0.8518
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3559 - accuracy: 0.8533
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3548 - accuracy: 0.8518
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8525
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3527 - accuracy: 0.8543
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3508 - accuracy: 0.8534
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8550
63/63 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.8600

[I 2024-03-13 14:59:17,988] Trial 9 finished with value: 0.34769245982170105 and parameters: {'n_layers': 1, 'n_units': 78, 'learning_rate': 0.0028776631163300163}. Best is trial 9 with value: 0.34769245982170105.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4063 - accuracy: 0.8271
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3695 - accuracy: 0.8479
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3649 - accuracy: 0.8509
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3623 - accuracy: 0.8506
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3598 - accuracy: 0.8528
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3602 - accuracy: 0.8514
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3528 - accuracy: 0.8554
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3527 - accuracy: 0.8576
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8541
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8556
63/63 [==============================] - 1s 1ms/step - loss: 0.3445 - accuracy: 0.8525

[I 2024-03-13 14:59:29,679] Trial 10 finished with value: 0.3445223271846771 and parameters: {'n_layers': 1, 'n_units': 33, 'learning_rate': 0.009984694523736945}. Best is trial 10 with value: 0.3445223271846771.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4132 - accuracy: 0.8269
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3693 - accuracy: 0.8485
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3653 - accuracy: 0.8505
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3622 - accuracy: 0.8514
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8504
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8514
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8520
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3547 - accuracy: 0.8550
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3524 - accuracy: 0.8558
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3501 - accuracy: 0.8565
63/63 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8630

[I 2024-03-13 14:59:36,060] Trial 11 finished with value: 0.3481663465499878 and parameters: {'n_layers': 1, 'n_units': 32, 'learning_rate': 0.0099120450307633}. Best is trial 10 with value: 0.3445223271846771.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.8080
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3705 - accuracy: 0.8476
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3622 - accuracy: 0.8504
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8544
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3576 - accuracy: 0.8526
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8555
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3517 - accuracy: 0.8555
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8546
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8543
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8550
63/63 [==============================] - 0s 1ms/step - loss: 0.3414 - accuracy: 0.8605

[I 2024-03-13 14:59:42,327] Trial 12 finished with value: 0.34140393137931824 and parameters: {'n_layers': 1, 'n_units': 32, 'learning_rate': 0.006548703099287154}. Best is trial 12 with value: 0.34140393137931824.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4077 - accuracy: 0.8300
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3618 - accuracy: 0.8497
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3579 - accuracy: 0.8533
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3548 - accuracy: 0.8541
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8530
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8524
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8565
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3473 - accuracy: 0.8549
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3482 - accuracy: 0.8558
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3473 - accuracy: 0.8556
63/63 [==============================] - 0s 2ms/step - loss: 0.3541 - accuracy: 0.8550

[I 2024-03-13 14:59:53,872] Trial 13 finished with value: 0.3540993928909302 and parameters: {'n_layers': 3, 'n_units': 34, 'learning_rate': 0.007404279414220205}. Best is trial 12 with value: 0.34140393137931824.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8332
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3682 - accuracy: 0.8504
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3574 - accuracy: 0.8541
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8547
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8546
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3511 - accuracy: 0.8566
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3510 - accuracy: 0.8571
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3453 - accuracy: 0.8576
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3448 - accuracy: 0.8571
63/63 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.8560

[I 2024-03-13 15:00:00,472] Trial 14 finished with value: 0.35370364785194397 and parameters: {'n_layers': 3, 'n_units': 74, 'learning_rate': 0.006232066376187584}. Best is trial 12 with value: 0.34140393137931824.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.3931 - accuracy: 0.8369
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3660 - accuracy: 0.8491
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8525
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3538 - accuracy: 0.8535
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3564 - accuracy: 0.8540
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3519 - accuracy: 0.8522
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8540
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8546
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8553
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3466 - accuracy: 0.8575
63/63 [==============================] - 0s 2ms/step - loss: 0.3534 - accuracy: 0.8600

[I 2024-03-13 15:00:07,138] Trial 15 finished with value: 0.35344448685646057 and parameters: {'n_layers': 2, 'n_units': 59, 'learning_rate': 0.008548326106736512}. Best is trial 12 with value: 0.34140393137931824.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4090 - accuracy: 0.8332
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3763 - accuracy: 0.8484
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3680 - accuracy: 0.8520
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3658 - accuracy: 0.8484
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3594 - accuracy: 0.8533
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3573 - accuracy: 0.8519
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3592 - accuracy: 0.8534
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3548 - accuracy: 0.8534
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3545 - accuracy: 0.8529
Epoch 10/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3519 - accuracy: 0.8549
63/63 [==============================] - 0s 3ms/step - loss: 0.3404 - accuracy: 0.8620

[I 2024-03-13 15:00:15,885] Trial 16 finished with value: 0.3404224216938019 and parameters: {'n_layers': 4, 'n_units': 113, 'learning_rate': 0.009769751374208803}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4113 - accuracy: 0.8322
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3700 - accuracy: 0.8493
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3633 - accuracy: 0.8512
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3628 - accuracy: 0.8491
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3552 - accuracy: 0.8514
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3536 - accuracy: 0.8528
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3573 - accuracy: 0.8579
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3507 - accuracy: 0.8544
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3507 - accuracy: 0.8534
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3502 - accuracy: 0.8550
63/63 [==============================] - 0s 3ms/step - loss: 0.3501 - accuracy: 0.8580

[I 2024-03-13 15:00:27,825] Trial 17 finished with value: 0.35005447268486023 and parameters: {'n_layers': 4, 'n_units': 104, 'learning_rate': 0.007933875685232216}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4126 - accuracy: 0.8307
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3735 - accuracy: 0.8495
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3645 - accuracy: 0.8515
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3557 - accuracy: 0.8528
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3610 - accuracy: 0.8528
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3591 - accuracy: 0.8516
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3559 - accuracy: 0.8551
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3548 - accuracy: 0.8570
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3528 - accuracy: 0.8529
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3492 - accuracy: 0.8568
63/63 [==============================] - 0s 3ms/step - loss: 0.3710 - accuracy: 0.8515

[I 2024-03-13 15:00:40,000] Trial 18 finished with value: 0.3709975779056549 and parameters: {'n_layers': 5, 'n_units': 150, 'learning_rate': 0.00644234102056511}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4089 - accuracy: 0.8340
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3681 - accuracy: 0.8496
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3610 - accuracy: 0.8529
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8539
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3530 - accuracy: 0.8545
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3556 - accuracy: 0.8522
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8528
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3533 - accuracy: 0.8549
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3476 - accuracy: 0.8550
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3454 - accuracy: 0.8577
63/63 [==============================] - 0s 2ms/step - loss: 0.3447 - accuracy: 0.8600

[I 2024-03-13 15:00:46,484] Trial 19 finished with value: 0.34473147988319397 and parameters: {'n_layers': 3, 'n_units': 99, 'learning_rate': 0.008861124834837716}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4030 - accuracy: 0.8332
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3648 - accuracy: 0.8519
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3588 - accuracy: 0.8543
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8539
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3542 - accuracy: 0.8539
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3501 - accuracy: 0.8566
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3506 - accuracy: 0.8550
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3485 - accuracy: 0.8556
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3461 - accuracy: 0.8581
Epoch 10/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3470 - accuracy: 0.8574
63/63 [==============================] - 0s 2ms/step - loss: 0.3647 - accuracy: 0.8525

[I 2024-03-13 15:00:57,842] Trial 20 finished with value: 0.36465537548065186 and parameters: {'n_layers': 2, 'n_units': 145, 'learning_rate': 0.0053799286996420856}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4036 - accuracy: 0.8364
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3679 - accuracy: 0.8485
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3624 - accuracy: 0.8493
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8541
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8529
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8531
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8562
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3497 - accuracy: 0.8551
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3512 - accuracy: 0.8572
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8545
63/63 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8610

[I 2024-03-13 15:01:02,931] Trial 21 finished with value: 0.3422519564628601 and parameters: {'n_layers': 1, 'n_units': 52, 'learning_rate': 0.009978388920583534}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3930 - accuracy: 0.8363
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3613 - accuracy: 0.8510
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8535
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3555 - accuracy: 0.8537
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3528 - accuracy: 0.8530
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3524 - accuracy: 0.8537
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8561
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3499 - accuracy: 0.8520
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3484 - accuracy: 0.8537
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3487 - accuracy: 0.8558
63/63 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8555

[I 2024-03-13 15:01:14,275] Trial 22 finished with value: 0.350247859954834 and parameters: {'n_layers': 2, 'n_units': 57, 'learning_rate': 0.009311121180605996}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4007 - accuracy: 0.8342
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3687 - accuracy: 0.8482
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8464
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3600 - accuracy: 0.8518
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8525
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3526 - accuracy: 0.8554
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3515 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3529 - accuracy: 0.8549
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3488 - accuracy: 0.8556
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3482 - accuracy: 0.8550
63/63 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.8600

[I 2024-03-13 15:01:21,892] Trial 23 finished with value: 0.3536653518676758 and parameters: {'n_layers': 4, 'n_units': 54, 'learning_rate': 0.007977327466051091}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3969 - accuracy: 0.8390
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3660 - accuracy: 0.8493
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3615 - accuracy: 0.8510
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3556 - accuracy: 0.8525
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3535 - accuracy: 0.8524
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8534
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8554
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3480 - accuracy: 0.8559
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.8554
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.8572
63/63 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8600

[I 2024-03-13 15:01:27,853] Trial 24 finished with value: 0.34752365946769714 and parameters: {'n_layers': 2, 'n_units': 105, 'learning_rate': 0.007931981549481543}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4083 - accuracy: 0.8324
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3682 - accuracy: 0.8494
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3651 - accuracy: 0.8505
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3650 - accuracy: 0.8505
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3530 - accuracy: 0.8518
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3566 - accuracy: 0.8520
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3515 - accuracy: 0.8560
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3569 - accuracy: 0.8516
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3492 - accuracy: 0.8553
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3490 - accuracy: 0.8555
63/63 [==============================] - 0s 2ms/step - loss: 0.3538 - accuracy: 0.8570

[I 2024-03-13 15:01:35,980] Trial 25 finished with value: 0.3538123369216919 and parameters: {'n_layers': 5, 'n_units': 52, 'learning_rate': 0.00929295000815011}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4035 - accuracy: 0.8306
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3671 - accuracy: 0.8491
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3621 - accuracy: 0.8505
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3558 - accuracy: 0.8520
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3523 - accuracy: 0.8541
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8540
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3489 - accuracy: 0.8569
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8549
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3487 - accuracy: 0.8534
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3472 - accuracy: 0.8546
63/63 [==============================] - 0s 1ms/step - loss: 0.3423 - accuracy: 0.8605

[I 2024-03-13 15:01:41,294] Trial 26 finished with value: 0.34229210019111633 and parameters: {'n_layers': 1, 'n_units': 87, 'learning_rate': 0.00688441411956443}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4509 - accuracy: 0.8062
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3727 - accuracy: 0.8457
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3561 - accuracy: 0.8534
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3502 - accuracy: 0.8561
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3462 - accuracy: 0.8550
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3447 - accuracy: 0.8550
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3399 - accuracy: 0.8602
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8585
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8587
Epoch 10/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3345 - accuracy: 0.8597
63/63 [==============================] - 0s 2ms/step - loss: 0.3464 - accuracy: 0.8600

[I 2024-03-13 15:01:52,805] Trial 27 finished with value: 0.34640172123908997 and parameters: {'n_layers': 3, 'n_units': 126, 'learning_rate': 0.00030883376974605737}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.3982 - accuracy: 0.8360
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3657 - accuracy: 0.8516
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3614 - accuracy: 0.8529
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3588 - accuracy: 0.8509
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8524
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.8528
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3526 - accuracy: 0.8525
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8549
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3512 - accuracy: 0.8553
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3479 - accuracy: 0.8549
63/63 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8595

[I 2024-03-13 15:01:59,952] Trial 28 finished with value: 0.3508605360984802 and parameters: {'n_layers': 2, 'n_units': 66, 'learning_rate': 0.009386100971676673}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4010 - accuracy: 0.8314
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3667 - accuracy: 0.8489
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3684 - accuracy: 0.8506
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3605 - accuracy: 0.8497
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3580 - accuracy: 0.8521
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3614 - accuracy: 0.8516
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3534 - accuracy: 0.8541
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3583 - accuracy: 0.8550
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3551 - accuracy: 0.8514
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3506 - accuracy: 0.8555
63/63 [==============================] - 0s 2ms/step - loss: 0.3487 - accuracy: 0.8550

[I 2024-03-13 15:02:12,634] Trial 29 finished with value: 0.348654180765152 and parameters: {'n_layers': 5, 'n_units': 46, 'learning_rate': 0.008357396171868068}. Best is trial 16 with value: 0.3404224216938019.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8316
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3664 - accuracy: 0.8481
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8505
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3570 - accuracy: 0.8546
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3556 - accuracy: 0.8530
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3551 - accuracy: 0.8533
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8550
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3512 - accuracy: 0.8583
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8549
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3473 - accuracy: 0.8556
63/63 [==============================] - 0s 2ms/step - loss: 0.3404 - accuracy: 0.8600

[I 2024-03-13 15:02:18,964] Trial 30 finished with value: 0.34036752581596375 and parameters: {'n_layers': 1, 'n_units': 90, 'learning_rate': 0.007443459798129293}. Best is trial 30 with value: 0.34036752581596375.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4043 - accuracy: 0.8271
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3665 - accuracy: 0.8486
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3618 - accuracy: 0.8509
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3570 - accuracy: 0.8543
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3551 - accuracy: 0.8579
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3526 - accuracy: 0.8558
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8535
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3488 - accuracy: 0.8547
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8554
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8560
63/63 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8625

[I 2024-03-13 15:02:24,292] Trial 31 finished with value: 0.34232664108276367 and parameters: {'n_layers': 1, 'n_units': 90, 'learning_rate': 0.007267258553273709}. Best is trial 30 with value: 0.34036752581596375.

Epoch 1/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4049 - accuracy: 0.8288
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3670 - accuracy: 0.8501
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3631 - accuracy: 0.8505
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3598 - accuracy: 0.8540
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3544 - accuracy: 0.8521
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8545
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8545
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8530
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8560
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8554
63/63 [==============================] - 0s 2ms/step - loss: 0.3378 - accuracy: 0.8630

[I 2024-03-13 15:02:35,660] Trial 32 finished with value: 0.33776476979255676 and parameters: {'n_layers': 1, 'n_units': 116, 'learning_rate': 0.006567140705435349}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3962 - accuracy: 0.8394
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3664 - accuracy: 0.8493
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3579 - accuracy: 0.8528
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3538 - accuracy: 0.8535
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3532 - accuracy: 0.8546
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3517 - accuracy: 0.8562
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3491 - accuracy: 0.8572
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3482 - accuracy: 0.8561
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3455 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3458 - accuracy: 0.8583
63/63 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8595

[I 2024-03-13 15:02:43,062] Trial 33 finished with value: 0.34777888655662537 and parameters: {'n_layers': 2, 'n_units': 157, 'learning_rate': 0.005836151973765344}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4076 - accuracy: 0.8298
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3722 - accuracy: 0.8475
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3650 - accuracy: 0.8496
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3603 - accuracy: 0.8521
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3612 - accuracy: 0.8545
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3545 - accuracy: 0.8547
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3533 - accuracy: 0.8511
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3501 - accuracy: 0.8547
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3505 - accuracy: 0.8560
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3502 - accuracy: 0.8579
63/63 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8580

[I 2024-03-13 15:02:55,046] Trial 34 finished with value: 0.35712340474128723 and parameters: {'n_layers': 6, 'n_units': 120, 'learning_rate': 0.004849617705009393}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4169 - accuracy: 0.8249
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3877 - accuracy: 0.8413
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3709 - accuracy: 0.8475
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3619 - accuracy: 0.8539
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3629 - accuracy: 0.8522
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3645 - accuracy: 0.8544
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3630 - accuracy: 0.8519
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3546 - accuracy: 0.8543
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3542 - accuracy: 0.8524
Epoch 10/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3511 - accuracy: 0.8555
63/63 [==============================] - 0s 3ms/step - loss: 0.3490 - accuracy: 0.8595

[I 2024-03-13 15:03:05,919] Trial 35 finished with value: 0.3490484952926636 and parameters: {'n_layers': 7, 'n_units': 135, 'learning_rate': 0.006407384949464101}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4088 - accuracy: 0.8319
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3662 - accuracy: 0.8505
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8516
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3580 - accuracy: 0.8521
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3555 - accuracy: 0.8544
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8555
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3508 - accuracy: 0.8570
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8539
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3488 - accuracy: 0.8553
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3476 - accuracy: 0.8566
63/63 [==============================] - 0s 2ms/step - loss: 0.3407 - accuracy: 0.8645

[I 2024-03-13 15:03:11,262] Trial 36 finished with value: 0.34071701765060425 and parameters: {'n_layers': 1, 'n_units': 113, 'learning_rate': 0.005773315698940869}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4000 - accuracy: 0.8311
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3655 - accuracy: 0.8499
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3568 - accuracy: 0.8524
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3538 - accuracy: 0.8553
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3527 - accuracy: 0.8556
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3515 - accuracy: 0.8564
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3497 - accuracy: 0.8533
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3482 - accuracy: 0.8576
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3507 - accuracy: 0.8558
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3444 - accuracy: 0.8580
63/63 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8575

[I 2024-03-13 15:03:18,677] Trial 37 finished with value: 0.3494328558444977 and parameters: {'n_layers': 3, 'n_units': 113, 'learning_rate': 0.005699567651320759}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8330
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3658 - accuracy: 0.8491
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3599 - accuracy: 0.8503
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3558 - accuracy: 0.8539
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3519 - accuracy: 0.8562
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3493 - accuracy: 0.8566
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3469 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8565
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3440 - accuracy: 0.8591
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3443 - accuracy: 0.8602
63/63 [==============================] - 0s 2ms/step - loss: 0.3504 - accuracy: 0.8550

[I 2024-03-13 15:03:26,374] Trial 38 finished with value: 0.3504374325275421 and parameters: {'n_layers': 4, 'n_units': 133, 'learning_rate': 0.004215833118715466}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4022 - accuracy: 0.8349
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3635 - accuracy: 0.8519
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3598 - accuracy: 0.8514
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3562 - accuracy: 0.8550
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8555
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3529 - accuracy: 0.8528
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3508 - accuracy: 0.8558
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3484 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3518 - accuracy: 0.8564
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3460 - accuracy: 0.8560
63/63 [==============================] - 0s 2ms/step - loss: 0.3449 - accuracy: 0.8635

[I 2024-03-13 15:03:37,709] Trial 39 finished with value: 0.34492045640945435 and parameters: {'n_layers': 2, 'n_units': 111, 'learning_rate': 0.007471570540171384}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 4ms/step - loss: 0.4160 - accuracy: 0.8276
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3819 - accuracy: 0.8440
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3770 - accuracy: 0.8469
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3779 - accuracy: 0.8510
Epoch 5/10
250/250 [==============================] - 1s 6ms/step - loss: 0.3732 - accuracy: 0.8510
Epoch 6/10
250/250 [==============================] - 2s 6ms/step - loss: 0.3622 - accuracy: 0.8506
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3572 - accuracy: 0.8512
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3556 - accuracy: 0.8493
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3557 - accuracy: 0.8534
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3535 - accuracy: 0.8551
63/63 [==============================] - 0s 2ms/step - loss: 0.3570 - accuracy: 0.8590

[I 2024-03-13 15:03:50,171] Trial 40 finished with value: 0.3569951355457306 and parameters: {'n_layers': 7, 'n_units': 168, 'learning_rate': 0.005020563392875884}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4081 - accuracy: 0.8325
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3663 - accuracy: 0.8519
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8489
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3591 - accuracy: 0.8509
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3585 - accuracy: 0.8539
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3538 - accuracy: 0.8570
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3526 - accuracy: 0.8546
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3495 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3508 - accuracy: 0.8551
63/63 [==============================] - 0s 1ms/step - loss: 0.3405 - accuracy: 0.8600

[I 2024-03-13 15:03:55,513] Trial 41 finished with value: 0.34053152799606323 and parameters: {'n_layers': 1, 'n_units': 92, 'learning_rate': 0.0065719240015945386}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4085 - accuracy: 0.8305
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3674 - accuracy: 0.8493
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3624 - accuracy: 0.8501
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3566 - accuracy: 0.8565
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3539 - accuracy: 0.8537
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3546 - accuracy: 0.8535
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3508 - accuracy: 0.8554
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3504 - accuracy: 0.8565
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3469 - accuracy: 0.8570
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3492 - accuracy: 0.8558
63/63 [==============================] - 0s 1ms/step - loss: 0.3448 - accuracy: 0.8575

[I 2024-03-13 15:04:06,657] Trial 42 finished with value: 0.3448275029659271 and parameters: {'n_layers': 1, 'n_units': 90, 'learning_rate': 0.0061069068846479405}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4003 - accuracy: 0.8324
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3681 - accuracy: 0.8482
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3641 - accuracy: 0.8504
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3594 - accuracy: 0.8506
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3585 - accuracy: 0.8533
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3566 - accuracy: 0.8545
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3542 - accuracy: 0.8535
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3522 - accuracy: 0.8539
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3494 - accuracy: 0.8543
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3488 - accuracy: 0.8562
63/63 [==============================] - 0s 2ms/step - loss: 0.3396 - accuracy: 0.8600

[I 2024-03-13 15:04:12,975] Trial 43 finished with value: 0.3396359980106354 and parameters: {'n_layers': 1, 'n_units': 97, 'learning_rate': 0.00531118447479457}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4047 - accuracy: 0.8366
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3664 - accuracy: 0.8506
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8518
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3566 - accuracy: 0.8556
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3530 - accuracy: 0.8529
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3512 - accuracy: 0.8559
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8571
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3469 - accuracy: 0.8581
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8561
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8572
63/63 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8555

[I 2024-03-13 15:04:19,237] Trial 44 finished with value: 0.35494717955589294 and parameters: {'n_layers': 2, 'n_units': 97, 'learning_rate': 0.006845457865615701}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 3s 3ms/step - loss: 0.4233 - accuracy: 0.8210
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3713 - accuracy: 0.8494
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3652 - accuracy: 0.8469
Epoch 4/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3615 - accuracy: 0.8505
Epoch 5/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3585 - accuracy: 0.8537
Epoch 6/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3548 - accuracy: 0.8570
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3500 - accuracy: 0.8577
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3505 - accuracy: 0.8571
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3495 - accuracy: 0.8574
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3428 - accuracy: 0.8611
63/63 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8620

[I 2024-03-13 15:04:31,858] Trial 45 finished with value: 0.3564295470714569 and parameters: {'n_layers': 10, 'n_units': 74, 'learning_rate': 0.0027853289608069385}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4034 - accuracy: 0.8321
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3661 - accuracy: 0.8496
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8524
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3598 - accuracy: 0.8508
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3544 - accuracy: 0.8549
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8539
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8547
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8554
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3484 - accuracy: 0.8584
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3497 - accuracy: 0.8558
63/63 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8615

[I 2024-03-13 15:04:37,511] Trial 46 finished with value: 0.3419174551963806 and parameters: {'n_layers': 1, 'n_units': 254, 'learning_rate': 0.003985410282485324}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 4s 4ms/step - loss: 0.4148 - accuracy: 0.8244
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3698 - accuracy: 0.8490
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3719 - accuracy: 0.8491
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3698 - accuracy: 0.8526
Epoch 5/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3629 - accuracy: 0.8529
Epoch 6/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3558 - accuracy: 0.8522
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3575 - accuracy: 0.8536
Epoch 8/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3517 - accuracy: 0.8499
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3478 - accuracy: 0.8547
Epoch 10/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3490 - accuracy: 0.8536
63/63 [==============================] - 0s 3ms/step - loss: 0.3746 - accuracy: 0.8495

[I 2024-03-13 15:04:51,495] Trial 47 finished with value: 0.374583899974823 and parameters: {'n_layers': 8, 'n_units': 127, 'learning_rate': 0.003511106316715855}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3961 - accuracy: 0.8340
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3620 - accuracy: 0.8524
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3599 - accuracy: 0.8539
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3529 - accuracy: 0.8522
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3504 - accuracy: 0.8544
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3497 - accuracy: 0.8544
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3477 - accuracy: 0.8565
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8565
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3463 - accuracy: 0.8560
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8589
63/63 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.8530

[I 2024-03-13 15:04:58,160] Trial 48 finished with value: 0.3571576178073883 and parameters: {'n_layers': 3, 'n_units': 88, 'learning_rate': 0.00529846041616917}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4056 - accuracy: 0.8315
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3645 - accuracy: 0.8501
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3628 - accuracy: 0.8531
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.8525
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3579 - accuracy: 0.8526
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8529
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3510 - accuracy: 0.8539
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3521 - accuracy: 0.8535
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3501 - accuracy: 0.8562
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3486 - accuracy: 0.8564
63/63 [==============================] - 0s 2ms/step - loss: 0.3453 - accuracy: 0.8625

[I 2024-03-13 15:05:04,204] Trial 49 finished with value: 0.3453108072280884 and parameters: {'n_layers': 1, 'n_units': 71, 'learning_rate': 0.007700879797280276}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4001 - accuracy: 0.8360
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3594 - accuracy: 0.8520
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3555 - accuracy: 0.8528
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3505 - accuracy: 0.8554
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3496 - accuracy: 0.8536
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3484 - accuracy: 0.8577
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3448 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3415 - accuracy: 0.8580
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3414 - accuracy: 0.8561
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3403 - accuracy: 0.8580
63/63 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8520

[I 2024-03-13 15:05:11,155] Trial 50 finished with value: 0.35332393646240234 and parameters: {'n_layers': 2, 'n_units': 189, 'learning_rate': 0.002090397642402245}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4079 - accuracy: 0.8317
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3681 - accuracy: 0.8470
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3639 - accuracy: 0.8500
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3587 - accuracy: 0.8534
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3560 - accuracy: 0.8525
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8543
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8553
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3488 - accuracy: 0.8564
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8556
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8570
63/63 [==============================] - 0s 3ms/step - loss: 0.3431 - accuracy: 0.8595

[I 2024-03-13 15:05:17,483] Trial 51 finished with value: 0.3430815637111664 and parameters: {'n_layers': 1, 'n_units': 112, 'learning_rate': 0.004644607571361273}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8322
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3681 - accuracy: 0.8474
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3610 - accuracy: 0.8534
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3604 - accuracy: 0.8516
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3559 - accuracy: 0.8510
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8555
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8558
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3480 - accuracy: 0.8554
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8558
63/63 [==============================] - 0s 1ms/step - loss: 0.3457 - accuracy: 0.8600

[I 2024-03-13 15:05:24,255] Trial 52 finished with value: 0.3457438051700592 and parameters: {'n_layers': 1, 'n_units': 119, 'learning_rate': 0.005890977762228507}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4142 - accuracy: 0.8225
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3677 - accuracy: 0.8495
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3611 - accuracy: 0.8493
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3567 - accuracy: 0.8528
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3536 - accuracy: 0.8529
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8521
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8539
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8562
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3461 - accuracy: 0.8574
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3456 - accuracy: 0.8558
63/63 [==============================] - 0s 2ms/step - loss: 0.3399 - accuracy: 0.8605

[I 2024-03-13 15:05:29,761] Trial 53 finished with value: 0.339944064617157 and parameters: {'n_layers': 1, 'n_units': 82, 'learning_rate': 0.005371959200892883}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.3966 - accuracy: 0.8331
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3641 - accuracy: 0.8500
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3583 - accuracy: 0.8529
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3547 - accuracy: 0.8533
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8585
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3491 - accuracy: 0.8539
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3474 - accuracy: 0.8583
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3467 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3451 - accuracy: 0.8553
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8553
63/63 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8525

[I 2024-03-13 15:05:36,418] Trial 54 finished with value: 0.35389015078544617 and parameters: {'n_layers': 2, 'n_units': 82, 'learning_rate': 0.005348485224046038}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4042 - accuracy: 0.8299
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3658 - accuracy: 0.8510
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8534
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3550 - accuracy: 0.8543
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3546 - accuracy: 0.8570
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8565
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8553
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8551
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3472 - accuracy: 0.8572
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3489 - accuracy: 0.8565
63/63 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8595

[I 2024-03-13 15:05:42,475] Trial 55 finished with value: 0.34448298811912537 and parameters: {'n_layers': 1, 'n_units': 98, 'learning_rate': 0.006961430807522922}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.3930 - accuracy: 0.8374
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3650 - accuracy: 0.8479
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3576 - accuracy: 0.8544
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3568 - accuracy: 0.8514
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3522 - accuracy: 0.8540
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3491 - accuracy: 0.8568
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3497 - accuracy: 0.8562
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3495 - accuracy: 0.8566
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8560
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3450 - accuracy: 0.8561
63/63 [==============================] - 0s 2ms/step - loss: 0.3463 - accuracy: 0.8585

[I 2024-03-13 15:05:54,150] Trial 56 finished with value: 0.3463045656681061 and parameters: {'n_layers': 2, 'n_units': 103, 'learning_rate': 0.006598566990764417}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3998 - accuracy: 0.8359
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3748 - accuracy: 0.8471
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3589 - accuracy: 0.8540
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3561 - accuracy: 0.8544
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3554 - accuracy: 0.8550
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3536 - accuracy: 0.8540
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3505 - accuracy: 0.8543
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3497 - accuracy: 0.8543
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3479 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3454 - accuracy: 0.8561
63/63 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8525

[I 2024-03-13 15:06:02,047] Trial 57 finished with value: 0.3481103181838989 and parameters: {'n_layers': 3, 'n_units': 136, 'learning_rate': 0.006202697773984188}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8330
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3665 - accuracy: 0.8487
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8521
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3612 - accuracy: 0.8529
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3592 - accuracy: 0.8525
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8556
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8540
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3504 - accuracy: 0.8555
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8559
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3498 - accuracy: 0.8550
63/63 [==============================] - 0s 1ms/step - loss: 0.3457 - accuracy: 0.8565

[I 2024-03-13 15:06:08,106] Trial 58 finished with value: 0.3456527888774872 and parameters: {'n_layers': 1, 'n_units': 69, 'learning_rate': 0.008939998702708936}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3962 - accuracy: 0.8349
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3681 - accuracy: 0.8496
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3630 - accuracy: 0.8514
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3555 - accuracy: 0.8506
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3533 - accuracy: 0.8516
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3528 - accuracy: 0.8529
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3511 - accuracy: 0.8537
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3544 - accuracy: 0.8566
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8559
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8555
63/63 [==============================] - 0s 1ms/step - loss: 0.3478 - accuracy: 0.8620

[I 2024-03-13 15:06:15,012] Trial 59 finished with value: 0.3477911651134491 and parameters: {'n_layers': 2, 'n_units': 83, 'learning_rate': 0.008484899496255619}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4030 - accuracy: 0.8311
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3651 - accuracy: 0.8508
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3593 - accuracy: 0.8521
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3531 - accuracy: 0.8540
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3503 - accuracy: 0.8537
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3493 - accuracy: 0.8559
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3487 - accuracy: 0.8553
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3460 - accuracy: 0.8576
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3424 - accuracy: 0.8577
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3444 - accuracy: 0.8604
63/63 [==============================] - 0s 2ms/step - loss: 0.3508 - accuracy: 0.8560

[I 2024-03-13 15:06:26,661] Trial 60 finished with value: 0.35081982612609863 and parameters: {'n_layers': 4, 'n_units': 93, 'learning_rate': 0.003834139730551335}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4079 - accuracy: 0.8266
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3678 - accuracy: 0.8504
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8491
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.8524
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.8547
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8544
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8566
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3467 - accuracy: 0.8555
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3471 - accuracy: 0.8551
63/63 [==============================] - 0s 2ms/step - loss: 0.3397 - accuracy: 0.8585

[I 2024-03-13 15:06:31,885] Trial 61 finished with value: 0.3396654725074768 and parameters: {'n_layers': 1, 'n_units': 105, 'learning_rate': 0.005604712882075657}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4031 - accuracy: 0.8338
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3678 - accuracy: 0.8494
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8497
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3583 - accuracy: 0.8511
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8533
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3546 - accuracy: 0.8544
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3529 - accuracy: 0.8535
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3507 - accuracy: 0.8539
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3490 - accuracy: 0.8568
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3483 - accuracy: 0.8547
63/63 [==============================] - 0s 2ms/step - loss: 0.3472 - accuracy: 0.8540

[I 2024-03-13 15:06:38,136] Trial 62 finished with value: 0.3472074568271637 and parameters: {'n_layers': 1, 'n_units': 106, 'learning_rate': 0.005277008470849507}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4155 - accuracy: 0.8253
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3713 - accuracy: 0.8499
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3632 - accuracy: 0.8518
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3607 - accuracy: 0.8509
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8536
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.8535
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3534 - accuracy: 0.8544
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3546 - accuracy: 0.8551
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3554 - accuracy: 0.8543
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3529 - accuracy: 0.8554
63/63 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8590

[I 2024-03-13 15:06:43,252] Trial 63 finished with value: 0.350904256105423 and parameters: {'n_layers': 1, 'n_units': 62, 'learning_rate': 0.004663638468133064}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4080 - accuracy: 0.8309
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3687 - accuracy: 0.8496
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8505
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8518
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3584 - accuracy: 0.8534
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3552 - accuracy: 0.8528
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3526 - accuracy: 0.8558
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3484 - accuracy: 0.8559
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8529
63/63 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8600

[I 2024-03-13 15:06:48,681] Trial 64 finished with value: 0.3426115810871124 and parameters: {'n_layers': 1, 'n_units': 77, 'learning_rate': 0.006671856181857141}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.3971 - accuracy: 0.8361
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3652 - accuracy: 0.8491
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3607 - accuracy: 0.8526
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3562 - accuracy: 0.8494
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3548 - accuracy: 0.8526
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3524 - accuracy: 0.8554
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3487 - accuracy: 0.8579
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8561
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3454 - accuracy: 0.8540
63/63 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8540

[I 2024-03-13 15:06:55,522] Trial 65 finished with value: 0.3474518358707428 and parameters: {'n_layers': 2, 'n_units': 122, 'learning_rate': 0.007196533374225757}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4068 - accuracy: 0.8296
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3682 - accuracy: 0.8487
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3613 - accuracy: 0.8504
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3598 - accuracy: 0.8497
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3529 - accuracy: 0.8530
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3538 - accuracy: 0.8550
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3510 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3505 - accuracy: 0.8550
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3499 - accuracy: 0.8540
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8561
63/63 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8610

[I 2024-03-13 15:07:00,789] Trial 66 finished with value: 0.3418535888195038 and parameters: {'n_layers': 1, 'n_units': 96, 'learning_rate': 0.005490142359650399}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3936 - accuracy: 0.8356
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3593 - accuracy: 0.8504
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3554 - accuracy: 0.8521
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3536 - accuracy: 0.8521
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3502 - accuracy: 0.8540
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8541
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3488 - accuracy: 0.8579
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8571
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3463 - accuracy: 0.8581
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3434 - accuracy: 0.8581
63/63 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8600

[I 2024-03-13 15:07:12,283] Trial 67 finished with value: 0.35202550888061523 and parameters: {'n_layers': 2, 'n_units': 43, 'learning_rate': 0.006175493005315344}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3996 - accuracy: 0.8364
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3644 - accuracy: 0.8504
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3575 - accuracy: 0.8544
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3557 - accuracy: 0.8530
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3510 - accuracy: 0.8554
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3504 - accuracy: 0.8571
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3502 - accuracy: 0.8561
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3476 - accuracy: 0.8587
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3457 - accuracy: 0.8571
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3455 - accuracy: 0.8564
63/63 [==============================] - 0s 2ms/step - loss: 0.3529 - accuracy: 0.8630

[I 2024-03-13 15:07:20,142] Trial 68 finished with value: 0.35287681221961975 and parameters: {'n_layers': 3, 'n_units': 106, 'learning_rate': 0.005023428081493369}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3978 - accuracy: 0.8344
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8472
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3607 - accuracy: 0.8503
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3570 - accuracy: 0.8535
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3565 - accuracy: 0.8534
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3552 - accuracy: 0.8504
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3535 - accuracy: 0.8537
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3506 - accuracy: 0.8555
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3498 - accuracy: 0.8565
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3478 - accuracy: 0.8572
63/63 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8565

[I 2024-03-13 15:07:26,169] Trial 69 finished with value: 0.3489825427532196 and parameters: {'n_layers': 1, 'n_units': 226, 'learning_rate': 0.005975938591023498}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4181 - accuracy: 0.8254
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3766 - accuracy: 0.8455
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3675 - accuracy: 0.8497
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3617 - accuracy: 0.8541
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3643 - accuracy: 0.8534
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3578 - accuracy: 0.8529
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3579 - accuracy: 0.8525
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3504 - accuracy: 0.8539
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3535 - accuracy: 0.8537
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3484 - accuracy: 0.8560
63/63 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8540

[I 2024-03-13 15:07:38,154] Trial 70 finished with value: 0.3699747920036316 and parameters: {'n_layers': 6, 'n_units': 82, 'learning_rate': 0.007590335812500763}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4081 - accuracy: 0.8273
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3671 - accuracy: 0.8457
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3615 - accuracy: 0.8529
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8514
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3559 - accuracy: 0.8515
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3538 - accuracy: 0.8533
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3511 - accuracy: 0.8560
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3495 - accuracy: 0.8544
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3504 - accuracy: 0.8544
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3478 - accuracy: 0.8577
63/63 [==============================] - 0s 2ms/step - loss: 0.3435 - accuracy: 0.8595

[I 2024-03-13 15:07:44,449] Trial 71 finished with value: 0.34348398447036743 and parameters: {'n_layers': 1, 'n_units': 114, 'learning_rate': 0.0057935166370678606}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4045 - accuracy: 0.8320
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3671 - accuracy: 0.8496
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3648 - accuracy: 0.8495
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3613 - accuracy: 0.8515
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3570 - accuracy: 0.8554
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8525
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3516 - accuracy: 0.8547
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8520
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8561
63/63 [==============================] - 0s 2ms/step - loss: 0.3447 - accuracy: 0.8545

[I 2024-03-13 15:07:49,872] Trial 72 finished with value: 0.3447214663028717 and parameters: {'n_layers': 1, 'n_units': 143, 'learning_rate': 0.004447468298423103}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4004 - accuracy: 0.8355
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3707 - accuracy: 0.8474
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3602 - accuracy: 0.8541
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3585 - accuracy: 0.8520
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3589 - accuracy: 0.8510
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3563 - accuracy: 0.8525
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3534 - accuracy: 0.8522
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3543 - accuracy: 0.8540
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3486 - accuracy: 0.8559
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3498 - accuracy: 0.8553
63/63 [==============================] - 0s 3ms/step - loss: 0.3470 - accuracy: 0.8600

[I 2024-03-13 15:07:58,498] Trial 73 finished with value: 0.3469841480255127 and parameters: {'n_layers': 2, 'n_units': 127, 'learning_rate': 0.009630179369335995}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3998 - accuracy: 0.8316
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3641 - accuracy: 0.8511
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3617 - accuracy: 0.8518
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3574 - accuracy: 0.8529
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.8569
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3529 - accuracy: 0.8556
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3521 - accuracy: 0.8535
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8536
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3504 - accuracy: 0.8575
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3492 - accuracy: 0.8574
63/63 [==============================] - 0s 2ms/step - loss: 0.3454 - accuracy: 0.8620

[I 2024-03-13 15:08:04,616] Trial 74 finished with value: 0.3453924059867859 and parameters: {'n_layers': 1, 'n_units': 108, 'learning_rate': 0.008078023246137118}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3926 - accuracy: 0.8350
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3651 - accuracy: 0.8489
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3574 - accuracy: 0.8508
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3533 - accuracy: 0.8539
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3528 - accuracy: 0.8561
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3520 - accuracy: 0.8560
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3491 - accuracy: 0.8562
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3468 - accuracy: 0.8593
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3466 - accuracy: 0.8577
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3452 - accuracy: 0.8575
63/63 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8625

[I 2024-03-13 15:08:12,101] Trial 75 finished with value: 0.34963884949684143 and parameters: {'n_layers': 2, 'n_units': 101, 'learning_rate': 0.006428620417496983}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4042 - accuracy: 0.8289
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3680 - accuracy: 0.8494
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8494
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8504
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3536 - accuracy: 0.8544
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3531 - accuracy: 0.8537
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8534
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8561
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8545
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8564
63/63 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8550

[I 2024-03-13 15:08:18,138] Trial 76 finished with value: 0.3509499132633209 and parameters: {'n_layers': 1, 'n_units': 118, 'learning_rate': 0.005628062311688772}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4084 - accuracy: 0.8294
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3673 - accuracy: 0.8500
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3615 - accuracy: 0.8515
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8550
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3560 - accuracy: 0.8547
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8543
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3527 - accuracy: 0.8536
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3508 - accuracy: 0.8558
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8561
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3485 - accuracy: 0.8550
63/63 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.8600

[I 2024-03-13 15:08:29,283] Trial 77 finished with value: 0.3419606387615204 and parameters: {'n_layers': 1, 'n_units': 92, 'learning_rate': 0.004830931542995953}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4104 - accuracy: 0.8269
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3756 - accuracy: 0.8455
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3674 - accuracy: 0.8519
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3605 - accuracy: 0.8529
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3578 - accuracy: 0.8531
Epoch 6/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3576 - accuracy: 0.8525
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3506 - accuracy: 0.8560
Epoch 8/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3551 - accuracy: 0.8558
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3553 - accuracy: 0.8556
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3500 - accuracy: 0.8565
63/63 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8555

[I 2024-03-13 15:08:41,161] Trial 78 finished with value: 0.3500208258628845 and parameters: {'n_layers': 5, 'n_units': 130, 'learning_rate': 0.006765899811201078}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3912 - accuracy: 0.8364
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3625 - accuracy: 0.8512
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3579 - accuracy: 0.8526
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3594 - accuracy: 0.8535
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3558 - accuracy: 0.8518
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3512 - accuracy: 0.8539
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3500 - accuracy: 0.8574
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3511 - accuracy: 0.8555
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3522 - accuracy: 0.8551
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3469 - accuracy: 0.8559
63/63 [==============================] - 0s 2ms/step - loss: 0.3466 - accuracy: 0.8615

[I 2024-03-13 15:08:47,601] Trial 79 finished with value: 0.3465654253959656 and parameters: {'n_layers': 2, 'n_units': 141, 'learning_rate': 0.007127063721602833}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4117 - accuracy: 0.8281
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3677 - accuracy: 0.8495
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3641 - accuracy: 0.8482
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3592 - accuracy: 0.8521
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3559 - accuracy: 0.8531
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3545 - accuracy: 0.8570
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3508 - accuracy: 0.8547
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8555
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3473 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3468 - accuracy: 0.8568
63/63 [==============================] - 0s 1ms/step - loss: 0.3434 - accuracy: 0.8625

[I 2024-03-13 15:08:54,029] Trial 80 finished with value: 0.34336575865745544 and parameters: {'n_layers': 1, 'n_units': 152, 'learning_rate': 0.0031937648598230014}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4039 - accuracy: 0.8288
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3674 - accuracy: 0.8497
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3614 - accuracy: 0.8499
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8524
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3530 - accuracy: 0.8536
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8541
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8554
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8558
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.8569
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3483 - accuracy: 0.8561
63/63 [==============================] - 0s 2ms/step - loss: 0.3394 - accuracy: 0.8610

[I 2024-03-13 15:08:59,405] Trial 81 finished with value: 0.33943137526512146 and parameters: {'n_layers': 1, 'n_units': 86, 'learning_rate': 0.006455748407738767}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4064 - accuracy: 0.8264
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3673 - accuracy: 0.8478
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8479
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8514
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3569 - accuracy: 0.8511
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3544 - accuracy: 0.8553
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3562 - accuracy: 0.8526
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3559 - accuracy: 0.8549
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3539 - accuracy: 0.8560
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3523 - accuracy: 0.8547
63/63 [==============================] - 0s 1ms/step - loss: 0.3521 - accuracy: 0.8530

[I 2024-03-13 15:09:10,555] Trial 82 finished with value: 0.3521207869052887 and parameters: {'n_layers': 1, 'n_units': 63, 'learning_rate': 0.006329584041979386}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4069 - accuracy: 0.8304
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3676 - accuracy: 0.8503
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3641 - accuracy: 0.8511
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3592 - accuracy: 0.8530
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3578 - accuracy: 0.8512
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3566 - accuracy: 0.8536
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3557 - accuracy: 0.8543
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3517 - accuracy: 0.8544
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8545
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3491 - accuracy: 0.8554
63/63 [==============================] - 0s 2ms/step - loss: 0.3416 - accuracy: 0.8645

[I 2024-03-13 15:09:16,125] Trial 83 finished with value: 0.3415554165840149 and parameters: {'n_layers': 1, 'n_units': 85, 'learning_rate': 0.0055422611282450315}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.3954 - accuracy: 0.8353
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3611 - accuracy: 0.8489
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3550 - accuracy: 0.8545
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3530 - accuracy: 0.8547
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8522
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3517 - accuracy: 0.8544
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3480 - accuracy: 0.8561
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3469 - accuracy: 0.8553
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3451 - accuracy: 0.8568
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3454 - accuracy: 0.8561
63/63 [==============================] - 0s 1ms/step - loss: 0.3582 - accuracy: 0.8595

[I 2024-03-13 15:09:27,773] Trial 84 finished with value: 0.35815900564193726 and parameters: {'n_layers': 2, 'n_units': 91, 'learning_rate': 0.005191017477931154}. Best is trial 32 with value: 0.33776476979255676.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4052 - accuracy: 0.8279
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3681 - accuracy: 0.8478
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3615 - accuracy: 0.8510
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3587 - accuracy: 0.8520
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3562 - accuracy: 0.8531
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3517 - accuracy: 0.8553
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3506 - accuracy: 0.8539
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3492 - accuracy: 0.8559
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8546
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.8547
63/63 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8605

[I 2024-03-13 15:09:38,977] Trial 85 finished with value: 0.3376955986022949 and parameters: {'n_layers': 1, 'n_units': 99, 'learning_rate': 0.006005681151362595}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3971 - accuracy: 0.8375
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8504
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8528
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3552 - accuracy: 0.8533
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3524 - accuracy: 0.8568
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3506 - accuracy: 0.8580
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3515 - accuracy: 0.8551
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3473 - accuracy: 0.8551
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3472 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3469 - accuracy: 0.8553
63/63 [==============================] - 0s 1ms/step - loss: 0.3579 - accuracy: 0.8565

[I 2024-03-13 15:09:50,317] Trial 86 finished with value: 0.3579271137714386 and parameters: {'n_layers': 2, 'n_units': 77, 'learning_rate': 0.006642176935943432}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3999 - accuracy: 0.8382
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3679 - accuracy: 0.8496
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3610 - accuracy: 0.8544
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8533
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3540 - accuracy: 0.8556
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8508
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8546
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8540
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3480 - accuracy: 0.8541
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8577
63/63 [==============================] - 0s 2ms/step - loss: 0.3463 - accuracy: 0.8545

[I 2024-03-13 15:09:55,619] Trial 87 finished with value: 0.3462733328342438 and parameters: {'n_layers': 1, 'n_units': 100, 'learning_rate': 0.0073681341629516}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.3917 - accuracy: 0.8384
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3618 - accuracy: 0.8497
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3559 - accuracy: 0.8550
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3558 - accuracy: 0.8528
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3511 - accuracy: 0.8544
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8537
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3517 - accuracy: 0.8537
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3469 - accuracy: 0.8559
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3458 - accuracy: 0.8576
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8616
63/63 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8465

[I 2024-03-13 15:10:02,686] Trial 88 finished with value: 0.35280001163482666 and parameters: {'n_layers': 2, 'n_units': 96, 'learning_rate': 0.006073550361574432}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3985 - accuracy: 0.8370
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3673 - accuracy: 0.8495
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3615 - accuracy: 0.8511
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8501
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3561 - accuracy: 0.8533
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3557 - accuracy: 0.8521
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8551
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8556
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8545
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8549
63/63 [==============================] - 0s 1ms/step - loss: 0.3488 - accuracy: 0.8615

[I 2024-03-13 15:10:07,991] Trial 89 finished with value: 0.34879270195961 and parameters: {'n_layers': 1, 'n_units': 70, 'learning_rate': 0.00822213140016515}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4003 - accuracy: 0.8355
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3650 - accuracy: 0.8512
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3599 - accuracy: 0.8520
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3566 - accuracy: 0.8555
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3550 - accuracy: 0.8546
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3538 - accuracy: 0.8581
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8562
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3491 - accuracy: 0.8526
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3467 - accuracy: 0.8544
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8568
63/63 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.8590

[I 2024-03-13 15:10:15,177] Trial 90 finished with value: 0.34210482239723206 and parameters: {'n_layers': 2, 'n_units': 116, 'learning_rate': 0.007673401576074905}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4050 - accuracy: 0.8275
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3667 - accuracy: 0.8494
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3621 - accuracy: 0.8515
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3596 - accuracy: 0.8508
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3565 - accuracy: 0.8530
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8550
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3519 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3517 - accuracy: 0.8555
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3467 - accuracy: 0.8571
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8545
63/63 [==============================] - 0s 1ms/step - loss: 0.3402 - accuracy: 0.8600

[I 2024-03-13 15:10:20,365] Trial 91 finished with value: 0.34022974967956543 and parameters: {'n_layers': 1, 'n_units': 88, 'learning_rate': 0.00577856681141406}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4072 - accuracy: 0.8307
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3675 - accuracy: 0.8506
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3633 - accuracy: 0.8534
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3602 - accuracy: 0.8530
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3562 - accuracy: 0.8524
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3525 - accuracy: 0.8540
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3512 - accuracy: 0.8559
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3487 - accuracy: 0.8561
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3520 - accuracy: 0.8553
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3497 - accuracy: 0.8544
63/63 [==============================] - 0s 2ms/step - loss: 0.3431 - accuracy: 0.8590

[I 2024-03-13 15:10:26,835] Trial 92 finished with value: 0.3431152105331421 and parameters: {'n_layers': 1, 'n_units': 87, 'learning_rate': 0.005757056174459889}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4041 - accuracy: 0.8299
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3675 - accuracy: 0.8493
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8520
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8496
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3545 - accuracy: 0.8561
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3562 - accuracy: 0.8514
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8574
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8564
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3490 - accuracy: 0.8551
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8562
63/63 [==============================] - 0s 2ms/step - loss: 0.3402 - accuracy: 0.8620

[I 2024-03-13 15:10:32,134] Trial 93 finished with value: 0.34023192524909973 and parameters: {'n_layers': 1, 'n_units': 79, 'learning_rate': 0.0070037214434993935}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 2s 3ms/step - loss: 0.4427 - accuracy: 0.8105
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3880 - accuracy: 0.8381
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3808 - accuracy: 0.8449
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3858 - accuracy: 0.8470
Epoch 5/10
250/250 [==============================] - 1s 5ms/step - loss: 0.3665 - accuracy: 0.8528
Epoch 6/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3622 - accuracy: 0.8525
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3603 - accuracy: 0.8518
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3583 - accuracy: 0.8508
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3541 - accuracy: 0.8550
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3567 - accuracy: 0.8534
63/63 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8525

[I 2024-03-13 15:10:44,639] Trial 94 finished with value: 0.36186808347702026 and parameters: {'n_layers': 9, 'n_units': 75, 'learning_rate': 0.006909433962227379}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4071 - accuracy: 0.8315
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3697 - accuracy: 0.8479
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3633 - accuracy: 0.8508
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3609 - accuracy: 0.8516
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8531
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3566 - accuracy: 0.8541
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3551 - accuracy: 0.8544
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8540
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8564
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8547
63/63 [==============================] - 0s 2ms/step - loss: 0.3437 - accuracy: 0.8590

[I 2024-03-13 15:10:50,036] Trial 95 finished with value: 0.34368273615837097 and parameters: {'n_layers': 1, 'n_units': 80, 'learning_rate': 0.005921813931809768}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4054 - accuracy: 0.8261
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3679 - accuracy: 0.8468
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3606 - accuracy: 0.8495
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3548 - accuracy: 0.8529
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3531 - accuracy: 0.8539
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8534
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8546
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.8562
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3458 - accuracy: 0.8541
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3495 - accuracy: 0.8530
63/63 [==============================] - 0s 2ms/step - loss: 0.3523 - accuracy: 0.8625

[I 2024-03-13 15:10:56,345] Trial 96 finished with value: 0.3522535264492035 and parameters: {'n_layers': 1, 'n_units': 110, 'learning_rate': 0.006357211729488447}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3991 - accuracy: 0.8330
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3656 - accuracy: 0.8490
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8503
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8539
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8535
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8539
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3527 - accuracy: 0.8544
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3521 - accuracy: 0.8560
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8564
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8550
63/63 [==============================] - 0s 2ms/step - loss: 0.3408 - accuracy: 0.8575

[I 2024-03-13 15:11:02,432] Trial 97 finished with value: 0.3408105671405792 and parameters: {'n_layers': 1, 'n_units': 123, 'learning_rate': 0.008686310523723654}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3975 - accuracy: 0.8345
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3622 - accuracy: 0.8520
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3585 - accuracy: 0.8530
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3538 - accuracy: 0.8546
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3513 - accuracy: 0.8571
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3494 - accuracy: 0.8547
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3473 - accuracy: 0.8555
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3472 - accuracy: 0.8570
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3455 - accuracy: 0.8571
Epoch 10/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3452 - accuracy: 0.8580
63/63 [==============================] - 0s 2ms/step - loss: 0.3514 - accuracy: 0.8525

[I 2024-03-13 15:11:13,733] Trial 98 finished with value: 0.35140496492385864 and parameters: {'n_layers': 2, 'n_units': 102, 'learning_rate': 0.005483191888748075}. Best is trial 85 with value: 0.3376955986022949.

Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.4000 - accuracy: 0.8328
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3697 - accuracy: 0.8520
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3602 - accuracy: 0.8526
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3555 - accuracy: 0.8534
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3542 - accuracy: 0.8559
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3498 - accuracy: 0.8553
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3488 - accuracy: 0.8568
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3467 - accuracy: 0.8564
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3467 - accuracy: 0.8562
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3438 - accuracy: 0.8566
63/63 [==============================] - 0s 2ms/step - loss: 0.3529 - accuracy: 0.8530

[I 2024-03-13 15:11:21,954] Trial 99 finished with value: 0.3528711497783661 and parameters: {'n_layers': 4, 'n_units': 94, 'learning_rate': 0.005172886782085698}. Best is trial 85 with value: 0.3376955986022949.

Best params: {'n_layers': 1, 'n_units': 99, 'learning_rate': 0.006005681151362595}
Best validation loss: 0.3376955986022949